# permissions for end users to view pulsartopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsartopic-viewer-role
rules:
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartopics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartopics/status
  verbs:
  - get
