# permissions for end users to edit pulsarconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarconnection-editor-role
rules:
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarconnections/status
  verbs:
  - get
