# permissions for end users to view pulsartenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsartenant-viewer-role
rules:
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartenants/status
  verbs:
  - get
