name: Release

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  release:
    permissions:
      packages: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Set environment variables
        run: |
          echo "BUILD_IMAGE=golang:1.21" >> $GITHUB_ENV
          echo "KO_DOCKER_REPO=axon-networks/pulsar-resources-operator" >> $GITHUB_ENV
        
      - name: Run mage.go Release
        run: go run mage.go Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}